/* wohnsignal — daten (prototyp, alle inserate sind beispieldaten) */
window.WS_DATA = {
  brand: {
    name: "wohnsignal",
    claim: "dein nächstes zuhause sendet schon.",
    sub: "Wohnungen und Häuser in Baden-Württemberg – klar beschrieben, ehrlich ausgezeichnet und ohne Umwege gefunden."
  },
  listings: [
    {
      id: "ws-001",
      foto: "assets/foto-ws-001.jpg",
      titel: "Helle 2,5-Zimmer-Wohnung nahe Straßenbahn",
      typ: "wohnung",
      angebot: "miete",
      ort: "Mannheim",
      kreis: "Stadtkreis Mannheim",
      plz: "68167",
      strasse: "Uhlandstraße 14",
      preisEur: 820,
      zimmer: 2.5,
      flaecheM2: 58,
      etage: "3. OG",
      verfuegbarAb: "01.10.2026",
      merkmale: ["balkon", "aufzug", "einbauküche", "kellerraum", "haustiere erlaubt"],
      beschreibung: "2,5-Zimmer-Wohnung im dritten Obergeschoss eines Mehrfamilienhauses von 1978. Die Küche wurde 2021 erneuert, das Bad hat ein Fenster. Straßenbahn- und Bushaltestelle liegen rund fünf Gehminuten entfernt.",
      sceneHint: "Stadtfassade mit Balkonreihen und Fahrleitungen im Abendlicht",
      neu: false
    },
    {
      id: "ws-002",
      foto: "assets/foto-ws-002.jpg",
      titel: "Kompaktes Studio mit Innenhofblick",
      typ: "studio",
      angebot: "miete",
      ort: "Heidelberg",
      kreis: "Stadtkreis Heidelberg",
      plz: "69117",
      strasse: "Kettengasse 3",
      preisEur: 730,
      zimmer: 1,
      flaecheM2: 32,
      etage: "4. OG",
      verfuegbarAb: "nach Vereinbarung",
      merkmale: ["einbauküche", "waschmaschinenanschluss", "fahrradkeller"],
      beschreibung: "Studio mit offener Küche und Duschbad im vierten Obergeschoss eines Altstadthauses — ohne Aufzug. Das Zimmer geht auf den ruhigen Innenhof, direkte Sonne gibt es vor allem am Vormittag.",
      sceneHint: "Kleines Zimmer mit grossem Fenster zum begruenten Innenhof, Morgenlicht",
      neu: true
    },
    {
      id: "ws-003",
      foto: "assets/foto-ws-003.jpg",
      titel: "Loft in ehemaliger Weberei",
      typ: "loft",
      angebot: "miete",
      ort: "Mannheim",
      kreis: "Stadtkreis Mannheim",
      plz: "68159",
      strasse: "Spinnereistraße 7",
      preisEur: 1750,
      zimmer: 3,
      flaecheM2: 118,
      etage: "2. OG",
      verfuegbarAb: "01.12.2026",
      merkmale: ["hohe decken", "aufzug", "einbauküche", "gäste-wc", "stellplatz zumietbar"],
      beschreibung: "Loft in einer umgebauten Weberei im Jungbusch mit 3,6 Metern Raumhöhe und Industriefenstern auf zwei Seiten. Zwei Zimmer sind abgetrennt, der Wohnbereich bleibt offen. Die Heizkosten fallen wegen des großen Volumens überdurchschnittlich aus.",
      sceneHint: "Industriefenster-Raster einer Backsteinfabrik mit hohen offenen Räumen dahinter",
      neu: false
    },
    {
      id: "ws-004",
      foto: "assets/foto-ws-004.jpg",
      titel: "3-Zimmer-Altbau im Gründerzeitviertel",
      typ: "wohnung",
      angebot: "miete",
      ort: "Heilbronn",
      kreis: "Stadtkreis Heilbronn",
      plz: "74072",
      strasse: "Rosenauweg 8",
      preisEur: 880,
      zimmer: 3,
      flaecheM2: 74,
      etage: "1. OG",
      verfuegbarAb: "01.11.2026",
      merkmale: ["balkon", "parkett", "einbauküche", "kellerraum", "speicheranteil"],
      beschreibung: "Wohnung im ersten Obergeschoss eines Hauses von 1936 mit Parkett in allen Zimmern. Der Balkon liegt zur Straßenseite, abends ist Verkehr hörbar. Läden und Grundschule sind zu Fuß erreichbar.",
      sceneHint: "Altbau-Fassade mit Sprossenfenstern und schmalem Balkon in warmem Nachmittagslicht",
      neu: false
    },
    {
      id: "ws-005",
      foto: "assets/foto-ws-005.jpg",
      titel: "4-Zimmer-Wohnung mit Gartenanteil",
      typ: "wohnung",
      angebot: "miete",
      ort: "Sinsheim",
      kreis: "Rhein-Neckar-Kreis",
      plz: "74889",
      strasse: "Steinackerstraße 21",
      preisEur: 1020,
      zimmer: 4,
      flaecheM2: 96,
      etage: "EG",
      verfuegbarAb: "01.10.2026",
      merkmale: ["gartenanteil", "haustiere erlaubt", "einbauküche", "kellerraum", "spielplatz im hof"],
      beschreibung: "Erdgeschosswohnung mit eigenem Gartenanteil nach Westen. Drei Schlafzimmer, Bad mit Wanne, separates WC. Die Wohnanlage stammt aus den 1990er-Jahren und wird abschnittsweise renoviert.",
      sceneHint: "Gartensitzplatz mit Hecke und Familientisch vor einer Wohnzeile, tiefe Abendsonne",
      neu: false
    },
    {
      id: "ws-006",
      foto: "assets/foto-ws-006.jpg",
      titel: "Altbauwohnung mit hohen Räumen",
      typ: "wohnung",
      angebot: "miete",
      ort: "Heidelberg",
      kreis: "Stadtkreis Heidelberg",
      plz: "69115",
      strasse: "Zähringerstraße 5",
      preisEur: 1420,
      zimmer: 3,
      flaecheM2: 82,
      etage: "2. OG",
      verfuegbarAb: "nach Vereinbarung",
      merkmale: ["hohe decken", "parkett", "einbauküche", "kellerraum", "fahrradkeller"],
      beschreibung: "3 Zimmer in einem Weststadt-Altbau mit gut drei Metern Raumhöhe und originalem Fischgrätparkett. Küche und Bad wurden 2019 ersetzt, ein Balkon fehlt. Der Neckar ist in zehn Gehminuten erreichbar.",
      sceneHint: "Hohe Altbaufenster mit Stuckdecke und Blick auf gegenüberliegende Dachlandschaft",
      neu: true
    },
    {
      id: "ws-007",
      foto: "assets/foto-ws-007.jpg",
      titel: "Moderne 4-Zimmer-Eigentumswohnung",
      typ: "wohnung",
      angebot: "kauf",
      ort: "Mannheim",
      kreis: "Stadtkreis Mannheim",
      plz: "68163",
      strasse: "Am Mühlbach 12",
      preisEur: 565000,
      zimmer: 4,
      flaecheM2: 105,
      etage: "3. OG",
      verfuegbarAb: "01.01.2027",
      merkmale: ["balkon", "aufzug", "kfw 55", "tg-stellplatz", "abstellraum", "gäste-wc"],
      beschreibung: "Eigentumswohnung aus dem Jahr 2019 mit Fußbodenheizung und kontrollierter Wohnraumlüftung, errichtet im KfW-55-Standard. Der Balkon ist nach Südosten ausgerichtet. Ein Tiefgaragenstellplatz ist im Preis enthalten.",
      sceneHint: "Klare Neubaufassade mit versetzten Balkonen und Baumreihe davor",
      neu: false
    },
    {
      id: "ws-008",
      foto: "assets/foto-ws-008.jpg",
      titel: "2-Zimmer-Wohnung im Hochparterre",
      typ: "wohnung",
      angebot: "miete",
      ort: "Mosbach",
      kreis: "Neckar-Odenwald-Kreis",
      plz: "74821",
      strasse: "Odenwaldring 9",
      preisEur: 560,
      zimmer: 2,
      flaecheM2: 54,
      etage: "Hochparterre",
      verfuegbarAb: "01.11.2026",
      merkmale: ["einbauküche", "kellerraum", "waschkeller im haus", "nahe öpnv"],
      beschreibung: "Wohnung im Hochparterre eines gepflegten Mehrfamilienhauses von 1965. Die Räume sind zweckmäßig geschnitten, das Bad ist innenliegend. Bushaltestelle und Bäcker liegen direkt um die Ecke.",
      sceneHint: "Ruhige Quartierstrasse mit Mehrfamilienhaus und Vorgartenmauer im Morgenlicht",
      neu: false
    },
    {
      id: "ws-009",
      foto: "assets/foto-ws-009.jpg",
      titel: "Penthouse mit Dachterrasse über dem Neckartal",
      typ: "penthouse",
      angebot: "miete",
      ort: "Eberbach",
      kreis: "Rhein-Neckar-Kreis",
      plz: "69412",
      strasse: "Obere Halde 4",
      preisEur: 1150,
      zimmer: 3,
      flaecheM2: 88,
      etage: "Dachgeschoss",
      verfuegbarAb: "01.12.2026",
      merkmale: ["dachterrasse", "neckarblick", "aufzug", "tg-stellplatz", "abstellraum"],
      beschreibung: "Penthouse mit umlaufender Dachterrasse und Blick über das Neckartal. Wohnbereich mit offener Küche, zwei Schlafzimmer, Bad mit Wanne. Im Sommer heizt sich die Südseite spürbar auf, außenliegende Raffstoren sind vorhanden.",
      sceneHint: "Dachterrasse mit Geländer, Flusstal und bewaldete Hügel in der Ferne, terrasse berg",
      neu: false
    },
    {
      id: "ws-010",
      foto: "assets/foto-ws-010.jpg",
      titel: "3-Zimmer-Wohnung nahe Neckarufer",
      typ: "wohnung",
      angebot: "miete",
      ort: "Neckargemünd",
      kreis: "Rhein-Neckar-Kreis",
      plz: "69151",
      strasse: "Elsenzweg 16",
      preisEur: 940,
      zimmer: 3,
      flaecheM2: 76,
      etage: "2. OG",
      verfuegbarAb: "01.10.2026",
      merkmale: ["balkon", "einbauküche", "kellerraum", "fahrradkeller", "haustiere erlaubt"],
      beschreibung: "Wohnung im zweiten Obergeschoss, rund sieben Gehminuten vom Neckarufer entfernt. Der Balkon zeigt nach Westen, die Küche ist aus den 2000er-Jahren und funktional. Parkplätze sind knapp, ein Außenstellplatz kann über eine Warteliste gemietet werden.",
      sceneHint: "Flusslauf mit Uferweg und Wohnhäusern, bewaldete Hänge im Hintergrund",
      neu: false
    },
    {
      id: "ws-011",
      foto: "assets/foto-ws-011.jpg",
      titel: "Penthouse mit Weitblick über das Neckartal",
      typ: "penthouse",
      angebot: "kauf",
      ort: "Heidelberg",
      kreis: "Stadtkreis Heidelberg",
      plz: "69126",
      strasse: "Sonnenhalde 2",
      preisEur: 795000,
      zimmer: 4,
      flaecheM2: 124,
      etage: "Dachgeschoss",
      verfuegbarAb: "nach Vereinbarung",
      merkmale: ["dachterrasse", "weitblick", "aufzug", "kfw 40", "tg-stellplatz", "kamin"],
      beschreibung: "Penthouse von 2022 mit 38 Quadratmetern Dachterrasse und freiem Blick über das Neckartal bis zum Odenwaldrand. Offener Wohnbereich, drei Zimmer, zwei Bäder. Zwei Tiefgaragenstellplätze können für je 35.000 Euro dazugekauft werden.",
      sceneHint: "Dachterrasse mit Hügelsilhouette und Abendhimmel in zwei Farbtoenen, terrasse berg",
      neu: true
    },
    {
      id: "ws-012",
      foto: "assets/foto-ws-012.jpg",
      titel: "2,5 Zimmer mit Blick über die Altstadt",
      typ: "wohnung",
      angebot: "miete",
      ort: "Mosbach",
      kreis: "Neckar-Odenwald-Kreis",
      plz: "74821",
      strasse: "Bergfeldweg 11",
      preisEur: 620,
      zimmer: 2.5,
      flaecheM2: 61,
      etage: "1. OG",
      verfuegbarAb: "01.11.2026",
      merkmale: ["balkon", "altstadtblick", "einbauküche", "kellerraum"],
      beschreibung: "Wohnung im ersten Obergeschoss eines Zweifamilienhauses am Hang, der Bahnhof Mosbach-Neckarelz ist mit dem Bus erreichbar. Vom Balkon aus blickt man über die Fachwerkdächer der Altstadt. An Markttagen ist im Viertel mit Suchverkehr zu rechnen.",
      sceneHint: "Wohnhaus mit Balkon vor bewaldeter Hügelkette, klare Sommerluft, berg",
      neu: false
    },
    {
      id: "ws-013",
      foto: "assets/foto-ws-013.jpg",
      titel: "Einfamilienhaus mit Garten und Werkstatt",
      typ: "haus",
      angebot: "kauf",
      ort: "Buchen",
      kreis: "Neckar-Odenwald-Kreis",
      plz: "74722",
      strasse: "Wacholderweg 6",
      preisEur: 329000,
      zimmer: 5,
      flaecheM2: 142,
      etage: "EG bis DG",
      verfuegbarAb: "01.03.2027",
      merkmale: ["garten", "garage", "kamin", "werkstatt", "randlage"],
      beschreibung: "Freistehendes Einfamilienhaus von 1962 mit 620 Quadratmetern Grundstück und angebauter Werkstatt am Ortsrand im Odenwald. Küche und Bäder wurden 2015 erneuert, die Ölheizung von 2008 dürfte mittelfristig zu ersetzen sein. Grundschule und Dorfladen sind in wenigen Minuten erreichbar.",
      sceneHint: "Einzelnes Haus mit Satteldach und Garten vor bewaldeten Hügeln",
      neu: false
    },
    {
      id: "ws-014",
      foto: "assets/foto-ws-014.jpg",
      titel: "Familienwohnung mit 4 Zimmern",
      typ: "wohnung",
      angebot: "miete",
      ort: "Heilbronn",
      kreis: "Stadtkreis Heilbronn",
      plz: "74081",
      strasse: "Eichendorffstraße 19",
      preisEur: 1150,
      zimmer: 4,
      flaecheM2: 102,
      etage: "1. OG",
      verfuegbarAb: "01.12.2026",
      merkmale: ["balkon", "aufzug", "einbauküche", "abstellraum", "spielplatz im hof", "haustiere erlaubt"],
      beschreibung: "4-Zimmer-Wohnung in einer Wohnanlage von 2008 mit Spielplatz im Innenhof. Drei Schlafzimmer, Bad mit Wanne und separates Dusch-WC. Der Hauptbahnhof ist mit dem Bus in etwa zehn Minuten erreichbar.",
      sceneHint: "Innenhof einer Wohnsiedlung mit Spielplatz und Baumgruppe am Nachmittag",
      neu: true
    },
    {
      id: "ws-015",
      foto: "assets/foto-ws-015.jpg",
      titel: "Reihenhaus über drei Etagen",
      typ: "haus",
      angebot: "kauf",
      ort: "Weinheim",
      kreis: "Rhein-Neckar-Kreis",
      plz: "69469",
      strasse: "Weiherholzweg 27",
      preisEur: 545000,
      zimmer: 5,
      flaecheM2: 156,
      etage: "EG bis 2. OG",
      verfuegbarAb: "nach Vereinbarung",
      merkmale: ["terrasse", "garage", "kellerraum", "gäste-wc", "hobbyraum"],
      beschreibung: "Mittleres Reihenhaus von 1998 an der Bergstraße mit Wohnraum über drei Etagen und ausgebautem Hobbyraum im Untergeschoss. Die Terrasse liegt nach Süden, die Fassade wurde 2020 neu gestrichen. Fenster und Heizung sind noch im Originalzustand.",
      sceneHint: "Reihenhauszeile mit kleinen Vorgärten und Garageneinfahrten im Spätlicht",
      neu: false
    },
    {
      id: "ws-016",
      foto: "assets/foto-ws-016.jpg",
      titel: "3-Zimmer-Eigentumswohnung mit Neckarblick",
      typ: "wohnung",
      angebot: "kauf",
      ort: "Heidelberg",
      kreis: "Stadtkreis Heidelberg",
      plz: "69120",
      strasse: "Am Neckarbogen 8",
      preisEur: 689000,
      zimmer: 3,
      flaecheM2: 92,
      etage: "4. OG",
      verfuegbarAb: "01.02.2027",
      merkmale: ["balkon", "aufzug", "neckarblick", "kfw 55", "tg-stellplatz"],
      beschreibung: "Eigentumswohnung von 2017 im vierten Obergeschoss in Neuenheim mit Blick auf den Neckar. Offene Küche, zwei Schlafzimmer, Bad und Dusch-WC. Das Hausgeld liegt bei rund 280 Euro pro Monat, ein Tiefgaragenstellplatz ist eingerechnet.",
      sceneHint: "Balkonblick über Dächer auf ruhige Wasserfläche, see",
      neu: false
    }
  ]
};
