/* wohnsignal — daten (prototyp, alle inserate sind beispieldaten) */
window.WS_DATA = {
  brand: {
    name: "wohnsignal",
    claim: "dein nächstes zuhause sendet schon.",
    sub: "Wohnungen und Häuser in der ganzen Schweiz – klar beschrieben, ehrlich ausgezeichnet und ohne Umwege gefunden."
  },
  listings: [
    {
      id: "ws-001",
      foto: "assets/foto-ws-001.jpg",
      titel: "Helle 2.5-Zimmer-Wohnung nahe Tramhalt",
      typ: "wohnung",
      angebot: "miete",
      ort: "Zürich",
      kanton: "ZH",
      plz: "8006",
      strasse: "Lindenrainstrasse 14",
      preisChf: 2380,
      zimmer: 2.5,
      flaecheM2: 58,
      etage: "3. OG",
      verfuegbarAb: "01.10.2026",
      merkmale: ["balkon", "lift", "einbauküche", "kellerabteil", "haustiere erlaubt"],
      beschreibung: "2.5-Zimmer-Wohnung im dritten Obergeschoss eines Mehrfamilienhauses von 1978. Die Küche wurde 2021 erneuert, das Bad hat ein Fenster. Tram- und Bushaltestelle liegen rund fünf Gehminuten entfernt.",
      sceneHint: "Stadtfassade mit Balkonreihen und Tramfahrleitungen im Abendlicht",
      neu: false
    },
    {
      id: "ws-002",
      foto: "assets/foto-ws-002.jpg",
      titel: "Kompaktes Studio mit Innenhofblick",
      typ: "studio",
      angebot: "miete",
      ort: "Zürich",
      kanton: "ZH",
      plz: "8008",
      strasse: "Rebhaldenweg 3",
      preisChf: 1590,
      zimmer: 1.5,
      flaecheM2: 32,
      etage: "4. OG",
      verfuegbarAb: "nach Vereinbarung",
      merkmale: ["lift", "einbauküche", "waschturm", "velokeller"],
      beschreibung: "Studio mit offener Küche und Duschbad im vierten Obergeschoss. Das Zimmer geht auf den ruhigen Innenhof, direkte Sonne gibt es vor allem am Vormittag. Eigener Waschturm in der Wohnung.",
      sceneHint: "Kleines Zimmer mit grossem Fenster zum begruenten Innenhof, Morgenlicht",
      neu: true
    },
    {
      id: "ws-003",
      foto: "assets/foto-ws-003.jpg",
      titel: "Loft in ehemaliger Weberei",
      typ: "loft",
      angebot: "miete",
      ort: "Zürich",
      kanton: "ZH",
      plz: "8005",
      strasse: "Spinnereiplatz 7",
      preisChf: 3950,
      zimmer: 3.5,
      flaecheM2: 118,
      etage: "2. OG",
      verfuegbarAb: "01.12.2026",
      merkmale: ["hohe decken", "lift", "einbauküche", "gäste-wc", "parkplatz zumietbar"],
      beschreibung: "Loft in einer umgebauten Weberei mit 3.6 Metern Raumhöhe und Industriefenstern auf zwei Seiten. Zwei Zimmer sind abgetrennt, der Wohnbereich bleibt offen. Die Heizkosten fallen wegen des grossen Volumens überdurchschnittlich aus.",
      sceneHint: "Industriefenster-Raster einer Backsteinfabrik mit hohen offenen Räumen dahinter",
      neu: false
    },
    {
      id: "ws-004",
      foto: "assets/foto-ws-004.jpg",
      titel: "3.5 Zimmer im Quartier mit Altbaubestand",
      typ: "wohnung",
      angebot: "miete",
      ort: "Bern",
      kanton: "BE",
      plz: "3007",
      strasse: "Brunnmattweg 8",
      preisChf: 1980,
      zimmer: 3.5,
      flaecheM2: 74,
      etage: "1. OG",
      verfuegbarAb: "01.11.2026",
      merkmale: ["balkon", "parkett", "einbauküche", "kellerabteil", "estrichabteil"],
      beschreibung: "Wohnung im ersten Obergeschoss eines Hauses von 1936 mit Parkett in allen Zimmern. Der Balkon liegt zur Strassenseite, abends ist Verkehr hörbar. Läden und Schulhaus sind zu Fuss erreichbar.",
      sceneHint: "Altbau-Fassade mit Sprossenfenstern und schmalem Balkon in warmem Nachmittagslicht",
      neu: false
    },
    {
      id: "ws-005",
      foto: "assets/foto-ws-005.jpg",
      titel: "4.5-Zimmer-Wohnung mit Gartensitzplatz",
      typ: "wohnung",
      angebot: "miete",
      ort: "Bern",
      kanton: "BE",
      plz: "3018",
      strasse: "Steinackerstrasse 21",
      preisChf: 2290,
      zimmer: 4.5,
      flaecheM2: 96,
      etage: "EG",
      verfuegbarAb: "01.10.2026",
      merkmale: ["gartensitzplatz", "haustiere erlaubt", "einbauküche", "kellerabteil", "spielplatz im hof"],
      beschreibung: "Erdgeschosswohnung mit eigenem Gartensitzplatz nach Westen. Drei Schlafzimmer, Bad mit Wanne, separates WC. Die Überbauung stammt aus den 1990er-Jahren und wird etappenweise renoviert.",
      sceneHint: "Gartensitzplatz mit Hecke und Familientisch vor einer Wohnzeile, tiefe Abendsonne",
      neu: false
    },
    {
      id: "ws-006",
      foto: "assets/foto-ws-006.jpg",
      titel: "Altbauwohnung mit hohen Räumen",
      typ: "wohnung",
      angebot: "miete",
      ort: "Basel",
      kanton: "BS",
      plz: "4058",
      strasse: "Falkengässlein 5",
      preisChf: 1890,
      zimmer: 3.5,
      flaecheM2: 82,
      etage: "2. OG",
      verfuegbarAb: "nach Vereinbarung",
      merkmale: ["hohe decken", "parkett", "einbauküche", "kellerabteil", "velokeller"],
      beschreibung: "3.5 Zimmer in einem Basler Altbau mit gut drei Metern Raumhöhe und original Fischgratparkett. Küche und Bad wurden 2019 ersetzt, ein Balkon fehlt. Der Rhein ist in zehn Gehminuten erreichbar.",
      sceneHint: "Hohe Altbaufenster mit Stuckdecke und Blick auf gegenüberliegende Dachlandschaft",
      neu: true
    },
    {
      id: "ws-007",
      foto: "assets/foto-ws-007.jpg",
      titel: "Moderne 4.5-Zimmer-Eigentumswohnung",
      typ: "wohnung",
      angebot: "kauf",
      ort: "Basel",
      kanton: "BS",
      plz: "4052",
      strasse: "Am Mülibach 12",
      preisChf: 985000,
      zimmer: 4.5,
      flaecheM2: 105,
      etage: "3. OG",
      verfuegbarAb: "01.01.2027",
      merkmale: ["balkon", "lift", "minergie", "einstellplatz", "reduit", "gäste-wc"],
      beschreibung: "Eigentumswohnung aus dem Jahr 2019 mit Bodenheizung und kontrollierter Lüftung nach Minergie-Standard. Der Balkon ist gegen Südosten ausgerichtet. Ein Einstellplatz in der Tiefgarage ist im Preis enthalten.",
      sceneHint: "Klare Neubaufassade mit versetzten Balkonen und Baumreihe davor",
      neu: false
    },
    {
      id: "ws-008",
      foto: "assets/foto-ws-008.jpg",
      titel: "2.5 Zimmer im Hochparterre",
      typ: "wohnung",
      angebot: "miete",
      ort: "Luzern",
      kanton: "LU",
      plz: "6004",
      strasse: "Hofmattring 9",
      preisChf: 1720,
      zimmer: 2.5,
      flaecheM2: 54,
      etage: "Hochparterre",
      verfuegbarAb: "01.11.2026",
      merkmale: ["einbauküche", "kellerabteil", "waschküche im haus", "nahe öv"],
      beschreibung: "Wohnung im Hochparterre eines gepflegten Mehrfamilienhauses von 1965. Die Räume sind zweckmässig geschnitten, das Bad ist innenliegend. Bushaltestelle und Quartierladen liegen direkt um die Ecke.",
      sceneHint: "Ruhige Quartierstrasse mit Mehrfamilienhaus und Vorgartenmauer im Morgenlicht",
      neu: false
    },
    {
      id: "ws-009",
      foto: "assets/foto-ws-009.jpg",
      titel: "Attika mit Terrasse und Seesicht",
      typ: "attika",
      angebot: "miete",
      ort: "Luzern",
      kanton: "LU",
      plz: "6006",
      strasse: "Obere Wartegg 4",
      preisChf: 2950,
      zimmer: 3.5,
      flaecheM2: 88,
      etage: "Attikageschoss",
      verfuegbarAb: "01.12.2026",
      merkmale: ["terrasse", "seesicht", "lift", "einstellplatz", "reduit"],
      beschreibung: "Attikawohnung mit umlaufender Terrasse und Sicht auf einen Ausschnitt des Sees. Wohnbereich mit offener Küche, zwei Schlafzimmer, Bad mit Wanne. Im Sommer heizt sich die Terrassenseite spürbar auf, aussenliegende Storen sind vorhanden.",
      sceneHint: "Dachterrasse mit Geländer, Seefläche und Bergsilhouette in der Ferne",
      neu: false
    },
    {
      id: "ws-010",
      foto: "assets/foto-ws-010.jpg",
      titel: "3.5-Zimmer-Wohnung nahe Aare",
      typ: "wohnung",
      angebot: "miete",
      ort: "Thun",
      kanton: "BE",
      plz: "3600",
      strasse: "Uferweglistrasse 16",
      preisChf: 1680,
      zimmer: 3.5,
      flaecheM2: 76,
      etage: "2. OG",
      verfuegbarAb: "01.10.2026",
      merkmale: ["balkon", "einbauküche", "kellerabteil", "velokeller", "haustiere erlaubt"],
      beschreibung: "Wohnung im zweiten Obergeschoss, rund sieben Gehminuten von der Aare entfernt. Der Balkon zeigt nach Westen, die Küche ist aus den 2000er-Jahren und funktional. Parkplätze sind knapp, ein Aussenplatz kann auf Warteliste gemietet werden.",
      sceneHint: "Flusslauf mit Uferweg und Wohnhäusern, Berge im Hintergrund",
      neu: false
    },
    {
      id: "ws-011",
      foto: "assets/foto-ws-011.jpg",
      titel: "Attika-Eigentum mit Bergsicht über dem Aaretal",
      typ: "attika",
      angebot: "kauf",
      ort: "Thun",
      kanton: "BE",
      plz: "3604",
      strasse: "Sonnrainhalde 2",
      preisChf: 1185000,
      zimmer: 4.5,
      flaecheM2: 124,
      etage: "Attikageschoss",
      verfuegbarAb: "nach Vereinbarung",
      merkmale: ["terrasse", "bergsicht", "lift", "minergie", "einstellplatz", "cheminée"],
      beschreibung: "Attikawohnung von 2022 mit 38 Quadratmetern Terrasse und freier Sicht über das Aaretal bis zu den Voralpen. Offener Wohnbereich, drei Zimmer, zwei Nasszellen. Zwei Einstellplätze können für je 35000 Franken dazugekauft werden.",
      sceneHint: "Attika-Terrasse mit Bergsilhouette und Abendhimmel in zwei Farbtoenen",
      neu: true
    },
    {
      id: "ws-012",
      foto: "assets/foto-ws-012.jpg",
      titel: "2.5 Zimmer zwischen See und Bahnhof",
      typ: "wohnung",
      angebot: "miete",
      ort: "Interlaken",
      kanton: "BE",
      plz: "3800",
      strasse: "Jungfrauweg 11",
      preisChf: 1450,
      zimmer: 2.5,
      flaecheM2: 61,
      etage: "1. OG",
      verfuegbarAb: "01.11.2026",
      merkmale: ["balkon", "bergsicht", "einbauküche", "kellerabteil"],
      beschreibung: "Wohnung im ersten Obergeschoss eines Zweifamilienhauses, beide Bahnhöfe sind zu Fuss erreichbar. Vom Balkon aus sieht man die umliegenden Berge. In der Hochsaison ist im Quartier mit Touristenverkehr zu rechnen.",
      sceneHint: "Wohnhaus mit Balkon vor markanter Bergkette, klare Sommerluft",
      neu: false
    },
    {
      id: "ws-013",
      foto: "assets/foto-ws-013.jpg",
      titel: "Einfamilienhaus mit Garten und Werkstatt",
      typ: "haus",
      angebot: "kauf",
      ort: "Meiringen",
      kanton: "BE",
      plz: "3860",
      strasse: "Bachtelenweg 6",
      preisChf: 749000,
      zimmer: 5.5,
      flaecheM2: 142,
      etage: "EG bis DG",
      verfuegbarAb: "01.03.2027",
      merkmale: ["garten", "garage", "cheminée", "werkstatt", "bergsicht"],
      beschreibung: "Freistehendes Einfamilienhaus von 1962 mit 620 Quadratmetern Umschwung und angebauter Werkstatt. Küche und Bäder wurden 2015 erneuert, die Ölheizung von 2008 dürfte mittelfristig zu ersetzen sein. Schule und Dorfladen sind in wenigen Minuten erreichbar.",
      sceneHint: "Einzelnes Haus mit Satteldach und Garten vor steilen Bergflanken",
      neu: false
    },
    {
      id: "ws-014",
      foto: "assets/foto-ws-014.jpg",
      titel: "Familienwohnung mit 4.5 Zimmern",
      typ: "wohnung",
      angebot: "miete",
      ort: "Winterthur",
      kanton: "ZH",
      plz: "8400",
      strasse: "Eichgutstrasse 19",
      preisChf: 2320,
      zimmer: 4.5,
      flaecheM2: 102,
      etage: "1. OG",
      verfuegbarAb: "01.12.2026",
      merkmale: ["balkon", "lift", "einbauküche", "reduit", "spielplatz im hof", "haustiere erlaubt"],
      beschreibung: "4.5-Zimmer-Wohnung in einer Siedlung von 2008 mit Spielplatz im Innenhof. Drei Schlafzimmer, Bad mit Wanne und separates Dusch-WC. Der Bahnhof ist mit dem Bus in etwa zehn Minuten erreichbar.",
      sceneHint: "Innenhof einer Wohnsiedlung mit Spielplatz und Baumgruppe am Nachmittag",
      neu: true
    },
    {
      id: "ws-015",
      foto: "assets/foto-ws-015.jpg",
      titel: "Reiheneinfamilienhaus über drei Etagen",
      typ: "haus",
      angebot: "kauf",
      ort: "Winterthur",
      kanton: "ZH",
      plz: "8405",
      strasse: "Weiherholzweg 27",
      preisChf: 1290000,
      zimmer: 5.5,
      flaecheM2: 156,
      etage: "EG bis 2. OG",
      verfuegbarAb: "nach Vereinbarung",
      merkmale: ["gartensitzplatz", "garage", "kellerraum", "gäste-wc", "hobbyraum"],
      beschreibung: "Mittleres Reihenhaus von 1998 mit Wohnraum über drei Etagen und ausgebautem Hobbyraum im Untergeschoss. Der Gartensitzplatz liegt gegen Süden, die Fassade wurde 2020 neu gestrichen. Fenster und Heizung sind noch im Originalzustand.",
      sceneHint: "Reihenhauszeile mit kleinen Vorgärten und Garageneinfahrten im Spätlicht",
      neu: false
    },
    {
      id: "ws-016",
      foto: "assets/foto-ws-016.jpg",
      titel: "3.5-Zimmer-Eigentum mit Seesicht",
      typ: "wohnung",
      angebot: "kauf",
      ort: "Zug",
      kanton: "ZG",
      plz: "6300",
      strasse: "Rigiblickstrasse 8",
      preisChf: 1495000,
      zimmer: 3.5,
      flaecheM2: 92,
      etage: "4. OG",
      verfuegbarAb: "01.02.2027",
      merkmale: ["balkon", "lift", "seesicht", "minergie", "einstellplatz"],
      beschreibung: "Eigentumswohnung von 2017 im vierten Obergeschoss mit Blick auf den Zugersee. Offene Küche, zwei Schlafzimmer, Bad und Dusch-WC. Die Nebenkosten liegen bei rund 280 Franken pro Monat, ein Einstellplatz ist eingerechnet.",
      sceneHint: "Balkonblick über Dächer auf ruhige Seefläche mit einzelnem Segelboot",
      neu: false
    }
  ]
};
